/* ===================== Language switching (EN / FR) =====================
 *
 * The tool is used by French consultants but reports to an English-speaking
 * audience, so both matter. English stays the source of truth: a missing French
 * key falls back to English rather than showing a raw key.
 *
 * Static chrome carries data-i18n attributes (see shell_top.html); everything
 * rendered from JS goes through t().
 *
 * Note on content: the watch items themselves come from the agent in the
 * language each source was written in (French, German, Polish…). Switching the
 * interface does not translate them — that would mean paying for a translation
 * pass on every item, and a validator checking a legal text should read it in
 * its original wording anyway.
 */
"use strict";

const I18N = {
  en: {
    "role": "Role",
    "role.reader": "Reader",
    "role.validator": "Validator (NIS 2 core team)",
    "nav.overview": "Overview",
    "nav.countries": "Countries",
    "nav.inbox": "Watch inbox",
    "nav.insights": "Insights & KPIs",
    "nav.sources": "Sources",

    "inbox.title": "Watch inbox",
    "inbox.sub": "Items detected by the automated collection pipeline (official sources, press, community) plus manual inputs from consultants. Nothing is published to country records until a validator approves it.",
    "inbox.pending": "Pending validation",
    "inbox.processed": "Processed items",
    "inbox.none": "No processed items yet.",
    "inbox.noMatch": "No pending item matches these filters.",
    "inbox.search": "Search title or summary…",
    "inbox.allCountries": "All countries",
    "inbox.anyScore": "Any score",
    "inbox.score": "Score ≥",
    "inbox.anyDate": "Any date",
    "inbox.last7": "Last 7 days",
    "inbox.last30": "Last 30 days",
    "inbox.last90": "Last 90 days",
    "inbox.anySource": "Any source",
    "inbox.officialOnly": "Official only",
    "inbox.toVerify": "To verify",
    "inbox.group": "Group by country",
    "inbox.reset": "Reset",
    "inbox.count": "{n} of {total} pending",
    "inbox.euGroup": "EU-wide",
    "inbox.grpPending": "pending",
    "inbox.grpOfficial": "official",
    "inbox.grpVerify": "to verify",
    "inbox.grpCells": "with workbook cells",
    "inbox.grpNoRecord": "no country record — nothing to update in the workbook",

    "card.published": "Published",
    "card.detected": "Detected",
    "card.inForce": "In force",
    "card.open": "Open source ↗",
    "card.noLink": "No link provided",
    "card.excerptFallback": "Source text unavailable — showing the agent's summary instead.",
    "card.cells": "Cells to update in the comparative workbook",
    "card.cellsNote": "Suggested targets — confirm against the source before editing the workbook.",
    "card.ai": "AI analysis — synthesis and key points",
    "card.aiSynthesis": "Synthesis",
    "card.aiPoints": "Key points",
    "card.aiRelevance": "Relevance",
    "card.aiImpact": "Impact",
    "card.aiEntities": "Entities concerned",
    "card.aiAdvice": "Client advice",
    "card.aiNote": "Generated by the watch agent. Decision support — never a publication decision.",
    "card.validate": "Validate & publish",
    "card.reject": "Reject",
    "card.validateNote": "Validating appends the event to the {country} timeline and updates its record date.",
    "card.validatedBy": "Validated",
    "card.rejectedBy": "Rejected",
    "card.by": "by",
    "card.on": "on",

    "manual.title": "Add an entry manually",
    "manual.sub": "For information gathered outside the pipeline (sector working groups, peer exchanges…). Manual entries join the pending queue with a \"Manual\" source flag.",
    "manual.country": "Country",
    "manual.date": "Date",
    "manual.srcType": "Source type",
    "manual.srcName": "Source name",
    "manual.itemTitle": "Title",
    "manual.summary": "Summary / note",
    "manual.add": "Add to pending queue",
    "manual.needTitle": "A title is required.",
    "manual.optOfficial": "Official",
    "manual.optUnofficial": "Unofficial — to verify",
    "manual.optManual": "Manual — consultant input",
    "manual.phSrc": "e.g. sector working group",
    "manual.phTitle": "What happened?",
    "manual.phSum": "Context, implications, confidentiality flag…"
  },
  fr: {
    "role": "Rôle",
    "role.reader": "Lecteur",
    "role.validator": "Validateur (équipe NIS 2)",
    "nav.overview": "Vue d'ensemble",
    "nav.countries": "Pays",
    "nav.inbox": "File de veille",
    "nav.insights": "Analyses & KPI",
    "nav.sources": "Sources",

    "inbox.title": "File de veille",
    "inbox.sub": "Éléments détectés par la chaîne de collecte automatisée (sources officielles, presse, communauté) et saisies manuelles des consultants. Rien n'est publié sur une fiche pays sans validation.",
    "inbox.pending": "En attente de validation",
    "inbox.processed": "Éléments traités",
    "inbox.none": "Aucun élément traité pour l'instant.",
    "inbox.noMatch": "Aucun élément ne correspond à ces filtres.",
    "inbox.search": "Rechercher un titre ou un résumé…",
    "inbox.allCountries": "Tous les pays",
    "inbox.anyScore": "Tous les scores",
    "inbox.score": "Score ≥",
    "inbox.anyDate": "Toutes les dates",
    "inbox.last7": "7 derniers jours",
    "inbox.last30": "30 derniers jours",
    "inbox.last90": "90 derniers jours",
    "inbox.anySource": "Toutes les sources",
    "inbox.officialOnly": "Officielles uniquement",
    "inbox.toVerify": "À vérifier",
    "inbox.group": "Grouper par pays",
    "inbox.reset": "Réinitialiser",
    "inbox.count": "{n} sur {total} en attente",
    "inbox.euGroup": "Union européenne",
    "inbox.grpPending": "en attente",
    "inbox.grpOfficial": "officielles",
    "inbox.grpVerify": "à vérifier",
    "inbox.grpCells": "avec cellules du classeur",
    "inbox.grpNoRecord": "pas de fiche pays — rien à mettre à jour dans le classeur",

    "card.published": "Publié le",
    "card.detected": "Détecté le",
    "card.inForce": "En vigueur le",
    "card.open": "Ouvrir la source ↗",
    "card.noLink": "Aucun lien fourni",
    "card.excerptFallback": "Texte de la source indisponible — synthèse de l'agent affichée à la place.",
    "card.cells": "Cellules à mettre à jour dans le classeur comparatif",
    "card.cellsNote": "Cibles suggérées — à confirmer sur la source avant d'éditer le classeur.",
    "card.ai": "Analyse IA — synthèse et points clés",
    "card.aiSynthesis": "Synthèse",
    "card.aiPoints": "Points clés",
    "card.aiRelevance": "Pertinence",
    "card.aiImpact": "Impact",
    "card.aiEntities": "Entités concernées",
    "card.aiAdvice": "Recommandation client",
    "card.aiNote": "Produit par l'agent de veille. Aide à la décision — jamais une décision de publication.",
    "card.validate": "Valider et publier",
    "card.reject": "Rejeter",
    "card.validateNote": "La validation ajoute l'événement à la chronologie {country} et met à jour sa date de fiche.",
    "card.validatedBy": "Validé",
    "card.rejectedBy": "Rejeté",
    "card.by": "par",
    "card.on": "le",

    "manual.title": "Ajouter une entrée manuellement",
    "manual.sub": "Pour une information recueillie hors de la chaîne automatisée (groupes de travail sectoriels, échanges entre pairs…). Les saisies manuelles rejoignent la file avec une source « Manuelle ».",
    "manual.country": "Pays",
    "manual.date": "Date",
    "manual.srcType": "Type de source",
    "manual.srcName": "Nom de la source",
    "manual.itemTitle": "Titre",
    "manual.summary": "Résumé / note",
    "manual.add": "Ajouter à la file",
    "manual.needTitle": "Un titre est obligatoire.",
    "manual.optOfficial": "Officielle",
    "manual.optUnofficial": "Non officielle — à vérifier",
    "manual.optManual": "Manuelle — saisie consultant",
    "manual.phSrc": "ex. groupe de travail sectoriel",
    "manual.phTitle": "Que s'est-il passé ?",
    "manual.phSum": "Contexte, implications, confidentialité…"
  }
};

/* Default only. This file is bundled before app_part1.js, where `store` is
   declared with `let` — reading it here (even via typeof) would hit the temporal
   dead zone. app_part1.js calls initLang() once the store exists. */
let lang = "en";

function initLang(){
  if (store.lang === "fr" || store.lang === "en") lang = store.lang;
  applyStaticI18n();
}

/* Translate `key`, substituting {placeholders} from `vars`. */
function t(key, vars){
  let s = (I18N[lang] && I18N[lang][key]) || I18N.en[key] || key;
  if (vars) Object.keys(vars).forEach(k => { s = s.split("{" + k + "}").join(vars[k]); });
  return s;
}

/* Apply translations to the static chrome carrying data-i18n. */
function applyStaticI18n(){
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = t(el.dataset.i18n);
  });
  document.documentElement.lang = lang;
  document.querySelectorAll(".lang-switch button").forEach(b => {
    b.classList.toggle("on", b.dataset.lang === lang);
  });
}

function setLang(next){
  if (next === lang) return;
  lang = next;
  if (typeof store !== "undefined") { store.lang = lang; saveStore(); }
  applyStaticI18n();
  renderCurrent();
}

/* Dates follow the interface language, not the machine's locale. */
function fmtDateL(iso){
  if (!iso) return "";
  const d = new Date(iso + (iso.length === 10 ? "T00:00:00" : ""));
  if (isNaN(d)) return iso;
  return d.toLocaleDateString(lang === "fr" ? "fr-FR" : "en-GB",
                              { day: "numeric", month: "short", year: "numeric" });
}
